global class constructorCase {
    global String id{get;set;}
	global String nombre{get;set;}
    global String rut{get;set;}
    global String codCorredor{get;set;}
    global String nombreCorredor{get;set;}
    global String telefono{get;set;}
    global String email{get;set;}
    global String asunto{get;set;}
    global String motivo{get;set;}
    global String descripcion{get;set;}
    global String nombrePagador{get;set;}
    global String rutPagador{get;set;}
    global String banco{get;set;}
    global String tipoCuenta{get;set;}
    global String nCuenta{get;set;}
    global String emailConfirmacion{get;set;}
    global String nSiniestro{get;set;}
    global String relacionA{get;set;}
    global String motivoPerdida{get;set;}
    global String subTipo{get;set;}
    
    
    
}